### ISSUE TITLE
Create a page for contributors

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#11]

**Comment by Mridulbirla13** [comment]
Hey, Can you please provide description of the task?

**Comment by devansh016** [comment]
A webpage have to be created where we can add the profile of people who contributed to this project. The data of the contributor can be added to a json file.

**Comment by ashutoshkrris** [comment]
I would like to work on this issue.

**Comment by ashutoshkrris** [comment]
Thanks for assigning @devansh016 
I'd be fetching the data from a JSON file.
Please let me know what all contributor details should be included.

**Comment by devansh016** [comment]
We can start with their name and github profile link.

**Comment by ashutoshkrris** [comment]
Will it be okay if I use profile cards?

**Comment by devansh016** [comment]
Yes you use profile cards but keep it simple.

**Comment by ashutoshkrris** [comment]
Alright, thanks!

**Comment by devansh016** [comment]
@ashutoshkrris Thanks for the contribution. Excellent Work.

**Comment by ashutoshkrris** [comment]
@devansh016 
Add about contributors.json in the README so that whenever somebody contribute, they add their details in that file.
