### ISSUE TITLE
Enhance Readme

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#16]
You can add new screenshot of the website or anything else.

**Comment by ishan-gupt** [comment]
You need images of the ui to be added to the readme or something else also... explain... i can take it up

**Comment by ishan-gupt** [comment]
assign it to me for adding ui images

**Comment by devansh016** [comment]
add the images of the ui to the readme in mode light and darkmode.

**Comment by ishan-gupt** [comment]
it has no news in it, so the minimal news light and dark pages are blank

**Comment by devansh016** [comment]
Try https://minimal-news.herokuapp.com/
To make it work on your system you will need news.org api key.
