### ISSUE TITLE
Feature: Redesigned UI

### ISSUE THREAD

**Issue by aryan31200** [devansh016/Minimal-News#21]
You have made a fine project but I might be able to add certain design elements to make website even more appealing. I am thinking of making all articles into cards.

**Comment by devansh016** [comment]
The main goal of our website is to be minimal and less-distracting for our user. If making the articles into card don't make the website distracting for the user we can go ahead with it.

**Comment by aryan31200** [comment]
I am thinking something like this. Adding images from articles or image of website from where article is from(if image not available) and without that button, just click on card and go to website.

![card grids](https://www.quackit.com/pix/css/flexbox/examples/flexbox_cards_align-items_stretch.png)

**Comment by aryan31200** [comment]
If you think this UI will look good, then please assign me this issue, or you can give me any of other issues to fix or add in your website

**Comment by devansh016** [comment]
These UI changes wouldn't go well with the website.  Images and cards will make the website distracting and like any other news site. You can take up any other issue or optimise the flow of the website , changes logo or anything else.

**Comment by yashchaudhari008** [comment]
I would like to work on this. I have one minimal design.

SAMPLE:-
![image](https://user-images.githubusercontent.com/29065088/135705120-4de02d8a-b74c-4bd4-9949-50032213557e.png)

**Comment by devansh016** [comment]
It looks good @yashchaudhari008 You can go ahead.
