### ISSUE TITLE
Design a new favicon

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#24]

**Comment by yashchaudhari008** [comment]
I will try this. Any suggestion/requirement?

**Comment by devansh016** [comment]
size 32 x 32 px and should be clearly visible in both dark and light mode.

**Comment by abhinandant34** [comment]
Yeah, I can do this task.

**Comment by devansh016** [comment]
@abhinandant34 this had already been assigned.

**Comment by yashchaudhari008** [comment]
![Artboard](https://user-images.githubusercontent.com/29065088/135711016-f74d7be0-25b4-42f2-ad67-b8cf43b84fdd.png)
Check this out, it's simple and minimal.

**Comment by devansh016** [comment]
A logo will be better. I would not be able to accept this.

**Comment by yashchaudhari008** [comment]
What if i make blue accent newspaper like favicon/icon?

**Comment by devansh016** [comment]
Yeah that will a good.

**Comment by yashchaudhari008** [comment]
## FEW MINIMAL DESIGNS
(Can make black icon white and vice versa)

1.  ![image](https://user-images.githubusercontent.com/29065088/135725680-daab6207-39b8-4c44-a8dd-486a0e1d8b1b.png)
2.  ![image](https://user-images.githubusercontent.com/29065088/135725789-c41cf473-9382-4db3-ae9d-0a1812113251.png)
3.  ![image](https://user-images.githubusercontent.com/29065088/135725820-257853b9-bd17-4e1f-a387-3962d8cf4d56.png)
4.  ![image](https://user-images.githubusercontent.com/29065088/135725884-08e5f0c3-b017-4552-b145-f6161926408a.png)

Tell me if you want different options (non material icons, etc)

**Comment by devansh016** [comment]
We can go with the 2nd icon. If possible change the shade of blue to a little darker blue or you can send a pull request.
