### ISSUE TITLE
Feedback form changes

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#25]
"Get in Touch" should appear in center. Also while filling the form the text is not readable properly in active input box.

**Comment by rahulbhatt1899** [comment]
Hey, I'd like to contribute to this issue.

**Comment by abhinandant34** [comment]
I can do this task for you

**Comment by CoderNehal** [comment]
assign me this plz

**Comment by CoderNehal** [comment]
check out the PR

**Comment by rahulbhatt1899** [comment]
Thank you for assigning, would send a PR in some time.

**Comment by devansh016** [comment]
both the task should be done to get the PR approved

**Comment by CoderNehal** [comment]
@devansh016  Check out and Approve

**Comment by CoderNehal** [comment]
Check Now
