### ISSUE TITLE
scroll to top button 

### ISSUE THREAD

**Issue by vaishnav-sh** [devansh016/Minimal-News#29]
I would like to contribute by solving this issue for hacktoberfest

**Comment by devansh016** [comment]
@vaishnav-sh  Okay. You can go ahead.

**Comment by vaishnav-sh** [comment]
Where do I set the environment variables?

**Comment by devansh016** [comment]
You have to create a .env file in root folder and add the variable (mentioned in readme file). You can get api key from https://newsapi.org/ .

**Comment by TishaJhabak1014** [comment]
@devansh016 Sir, any new issues to be created to contribute or I can add features and raise a PR?

**Comment by devansh016** [comment]
@TishaJhabak1014 I have created a new issue you can contribute in it or add any feature and raise a PR.

**Comment by devansh016** [comment]
@vaishnav-sh are you still working on this issue?

**Comment by vaishnav-sh** [comment]
Yes! I'm almost done

**Comment by rizastoday** [comment]
is this done ? I've done made the features, but forgot to see that there was already an issue that was assigned
