### ISSUE TITLE
add all the contributors details in res/contributors.json file

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#33]

**Comment by TishaJhabak1014** [comment]
@devansh016 Can you describe a bit on what details are need to be added?

**Comment by devansh016** [comment]
{
      "name": "Devansh Chaudhary",
      "github_url": "https://github.com/devansh016",
      "image_url": "https://avatars.githubusercontent.com/u/58871818?s=96&v=4"
}

Here is a example, You have to add all the contributor details in the json file you can get contributor details from the repo.

**Comment by TishaJhabak1014** [comment]
@devansh016 Okay. Plz assign me this.

**Comment by TishaJhabak1014** [comment]
@devansh016 Raised a PR, also do the needful of adding `hacktorberfest-accepted` label.
