### ISSUE TITLE
Add a responsive footer

### ISSUE THREAD

**Issue by Sejal-16** [devansh016/Minimal-News#34]

**Comment by Sejal-16** [comment]
I would like to work on this

**Comment by devansh016** [comment]
Okay you can go ahead.

**Comment by Sejal-16** [comment]
Okay On It!  Do you want any specific content to be displayed in footer ? If so please tell.

**Comment by devansh016** [comment]
If possible add a button which redirect to 
/contributors .

**Comment by Sejal-16** [comment]
![image](https://user-images.githubusercontent.com/65293021/135747797-3ebe7622-c57b-404b-819a-0f76ba952494.png)

The footer looks like this. I have tested it for responsive. Shall I make a pull request? If any changes please tell.

**Comment by devansh016** [comment]
It is good you can make a PR and also add don't forget to add your details in contributors file.

**Comment by Sejal-16** [comment]
Yep:)

**Comment by devansh016** [comment]
@Sejal-16 Footer should be fixed at the bottom.
![Capture](https://user-images.githubusercontent.com/58871818/135750272-992a0f3d-ddb5-4547-9238-30917c275191.PNG)

**Comment by Sejal-16** [comment]
i have done position : fixed and bottom : 0 in css file but its difficult to figure it out as i dont have the api key

**Comment by devansh016** [comment]
Can you attach a screenshot please.

**Comment by Sejal-16** [comment]
![image](https://user-images.githubusercontent.com/65293021/135760065-d0c9967f-02e6-4e6d-aaf7-b59add880df2.png)

I have added those cards just for testing of working of the footer. 
Now as and when i increase the cards , the footer below and is fixed at the bottom. Please check at your side. I am committing these changes. 
thnx!

**Comment by Sejal-16** [comment]
https://user-images.githubusercontent.com/65293021/135760351-a3fc5afc-10fa-4a83-80db-39c981c561f1.mp4

I have added those "Jane Doe cards " just for testing of working of the footer. 
Now the behaviour of the footer is as shown in the video. If you are fine with it i will remove those cards and commit the changes.

**Comment by devansh016** [comment]
The footer should be only be seen when we are at the bottom.

**Comment by Sejal-16** [comment]
Okay On it !

**Comment by Sejal-16** [comment]
https://user-images.githubusercontent.com/65293021/135760742-bc5e1f8e-8e47-4a72-8e33-d37010c8e703.mp4

Now is it fine ? shall i commit them?

**Comment by devansh016** [comment]
It's good. You can send PR will accept.

**Comment by Sejal-16** [comment]
yep
