### ISSUE TITLE
Making app an "Progressive Web App"?

### ISSUE THREAD

**Issue by yashchaudhari008** [devansh016/Minimal-News#35]
## Are you planning to make app installable?
PWA makes website installable on any web supporting platform(Windows, Android, ChromeOS, etc)

**Comment by devansh016** [comment]
Yes we can make a Progressive Web App for android platfom.

**Comment by yashchaudhari008** [comment]
Great, will try to implement that.

**Comment by swaraj-ssk** [comment]
@devansh016 I am using Heroku for this. Should I use another if you don't want ?

**Comment by devansh016** [comment]
> @devansh016 I am using Heroku for this. Should I use another if you don't want ?

Heroku is fine.
