### ISSUE TITLE
Add instruction to make the first contribution

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#37]
should include
1. adding their details in res/contributors.json file.
2. things to avoid like removing whitespaces and sending a PR or adding only a single line.
3.  and other details.

please add points if I miss something.
All instruction to be added in readme file.

**Comment by KanishkKhurana** [comment]
please assign this issue to me !
i'd love to contribute and make the documentation better !
@devansh016

**Comment by devansh016** [comment]
should add a point to star the repo

**Comment by KanishkKhurana** [comment]
@devansh016 should these instructions be in the readme or the code of conduct file ?

**Comment by devansh016** [comment]
Readme
