### ISSUE TITLE
Footer color is not matching to the theme

### ISSUE THREAD

**Issue by preeti-14-7** [devansh016/Minimal-News#59]
I  will try to set this with proper colour and also it will also look good if u add your some social info below 
something like this.

![135764226-e77dac96-93c3-4125-85c8-0138ee45700e](https://user-images.githubusercontent.com/73853439/135764492-b8cbb999-a80a-4966-bbd3-c7f429d1b8ee.jpg)

**Comment by devansh016** [comment]
@preeti-14-7 Okay

**Comment by swaraj-ssk** [comment]
Can you assign me this one ?

**Comment by devansh016** [comment]
@swaraj-ssk this issue is already assigned.

**Comment by preeti-14-7** [comment]
> @preeti-14-7 Okay

Can you guide me to localhost this server i m not able to host it in my computer

**Comment by devansh016** [comment]
You can find the instruction in the readme. Make sure you have nodejs installed on your system.

**Comment by JahnaviKashyap19** [comment]
Can I work on this issue?
