### ISSUE TITLE
Footer obstructing the actual content + color of the footer

### ISSUE THREAD

**Issue by pranaygupta25** [devansh016/Minimal-News#62]
The current footer seems to have no top-margin and thus could possibly interfere with the content in case of some articles.

Also, the sudden use of accent color seems to pop out a bit too much

![image](https://user-images.githubusercontent.com/79076844/135812359-520a01fe-4ebb-4d26-883a-722d23dd141d.png)

**Comment by devansh016** [comment]
@pranaygupta25 A issue is already raised. #59 You can work on that
