### ISSUE TITLE
Null displaying for some news

### ISSUE THREAD

**Issue by devansh016** [devansh016/Minimal-News#63]
![null](https://user-images.githubusercontent.com/58871818/135823721-871f2b4c-05d1-4272-8cd0-faeebf9502ba.PNG)

**Comment by itsdharmxd** [comment]
Hey  **@devansh016**    please assign me this issue , i am interested  in it

**Comment by itsdharmxd** [comment]
Hey @devansh016  i have given a PR  please  review
