### ISSUE TITLE
Error in script.js & Contributors page

### ISSUE THREAD

**Issue by yashchaudhari008** [devansh016/Minimal-News#66]
**Describe the bug**
Bug in contributors page.

**To Reproduce**
Just check console of browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/29065088/135844772-5acc62e9-740d-4b11-b774-6db7c8e03781.png)

**Desktop:**
 - Device: Lenovo Legion Y540 
 - OS: Windows 10
 - Browser: Chrome v94

**Comment by Himanshu664** [comment]
I am working on it please assign @yashchaudhari008

**Comment by yashchaudhari008** [comment]
@devansh016

**Comment by devansh016** [comment]
![error](https://user-images.githubusercontent.com/58871818/135878561-ddc8d4e7-9b95-4f26-8c33-ddab9cb9870b.PNG)
Also the profile cards are overlapping the dark mode button in mobile devices.

**Comment by itsdharmxd** [comment]
Hey  **@devansh016** please assign in this i am working on this

**Comment by devansh016** [comment]
If we remove the scroll to top script from contributors page or add the button UI in contributors page the console log error will be solved.

**Comment by itsdharmxd** [comment]
@devansh016  yes right

**Comment by itsdharmxd** [comment]
Hey **@devansh016**  given PR for this issue please take  review

**Comment by yashchaudhari008** [comment]
Same bug in feedback page!
