### ISSUE TITLE
Some UI Errors

### ISSUE THREAD

**Issue by yashchaudhari008** [devansh016/Minimal-News#77]
**Describe the bug**
UI Issue likes color doesn't match with theme, too much elements to display in single line.

**Screenshots**
- Color Not Matching
![image](https://user-images.githubusercontent.com/29065088/136340281-81eac842-20c1-4288-aed7-1dee09b5ad05.png)
![image](https://user-images.githubusercontent.com/29065088/136340397-feb58cf2-fcfc-4461-a80a-ed623758d9d6.png)

- Alignment Errors
(Feedback, Contributors Page)
![image](https://user-images.githubusercontent.com/29065088/136340587-2677b72e-0768-451a-94ec-4bf6e7d8dae4.png)

- Congested Header (Maybe there should be responsive navbar)
![image](https://user-images.githubusercontent.com/29065088/136340991-9b21d866-ecc5-4aa0-a411-ec69dc969e5d.png)

**Comment by devansh016** [comment]
Working on this in issue #82

**Comment by yashchaudhari008** [comment]
Still, UI is inconsistent. Could you reopen this issue?

**Comment by devansh016** [comment]
#90
