### ISSUE TITLE
Add `package-lock.json` and `res/newsArticles.txt` to `.gitignore`.

### ISSUE THREAD

**Issue by Muhammed-Rahif** [devansh016/Minimal-News#80]
> @devansh016 What about adding that `package-lock.json` and `res/newsArticles.txt` to `.gitignore` ?!

Yes please add them to it. I already added the res/newsArticles.txt but still facing the issue

_Originally posted by @devansh016 in https://github.com/devansh016/Minimal-News/issues/78#issuecomment-937671969_

**Comment by drunkenlegend** [comment]
Hi, I would like to take it up!
