### ISSUE TITLE
Screenshots outdated

### ISSUE THREAD

**Issue by Muhammed-Rahif** [devansh016/Minimal-News#84]
### There is some updates on website ui, so screenshots need to be update.

**Comment by devansh016** [comment]
super fast

**Comment by devansh016** [comment]
> Yeah! I think hacktoberfest made this repo more active..!

Yes hacktoberfest gave this repo a new life. Actually this was my learning project. My first project using nodejs.

**Comment by devansh016** [comment]
Soon I will be adding a new project.
